# -*- coding: utf-8 -*-
"""if_else.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YyHK3IJdmddID3yRnmBpzMuUL2IlPRU7
"""

idade = int(input("Digite sua idade: "))

if idade >= 18: print("Maior de idade")
else: print("Menor de idade")